"""Build results/REPORT.md from results/summary.json + figures (numbers are
pulled from the run, never typed by hand)."""
from __future__ import annotations

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")


def f(x, n=3):
    try:
        return f"{float(x):.{n}f}"
    except (TypeError, ValueError):
        return str(x)


def pct(x):
    return f"{100 * float(x):.0f}%" if x is not None else "n/a"


def main():
    with open(os.path.join(RES, "summary.json"), encoding="utf-8") as fh:
        S = json.load(fh)
    P, O, Cc, env = S.get("poster", {}), S.get("owen", {}), S.get("curse", {}), S.get("environment", {})
    L = []
    w = L.append
    w("# Report: do individual-based populations reproduce the papers' mathematics?\n")
    w(f"_Auto-generated by `scripts/make_report.py` from `results/summary.json`. Profile `{env.get('profile')}`, "
      f"master seed `{env.get('master_seed')}`, Python {env.get('python')}, numpy {env.get('numpy')}, "
      f"numba {env.get('numba')}, run {env.get('timestamp')}._\n")
    w("Lines in figures are the deterministic oracle (the papers' equations). Dots, bands and animated points are the "
      "zero-leakage individual-based model (IBM), which only knows viabilities, recombination, inheritance rules, N "
      "and the founding genotypes.\n")

    # ---------------------------------------------------------------- poster
    w("## 1. Poster: two-locus haploid model of IaSC resolution (Samant et al.)\n")
    p0 = P.get("P0 one-locus polymorphism", {})
    w("### 1.1 The IaSC polymorphism (panel A)\n")
    w(f"* p* = ½ + ½(1/b − 1/a) is confirmed by iterating the recursion (max deviation "
      f"{f(p0.get('iterate_vs_formula'), 1)} — machine precision).")
    rm = p0.get("rmse_by_N", {})
    w(f"* IBM time-averaged A1 frequency vs p*: RMSE " + ", ".join(f"N={k}: {f(v)}" for k, v in rm.items()) +
      f"; max |error| at the largest N = {f(p0.get('max_abs_err_largeN'))}.")
    w("\n![](figures/P0_one_locus.png)\n")
    pc = P.get("P2c IaSC persistence", {})
    if pc:
        w(f"**Finite-population caveat (new).** The restoring eigenvalue at p* is only {f(pc.get('mu_min'), 4)}–"
          f"{f(pc.get('mu_max'), 5)}, so balancing selection is very weak, especially near the edges of the a-range. "
          "In the IBM, drift fixes one allele within hundreds to thousands of generations unless N is large. "
          "The deterministic model cannot show this: there, the conflict persists forever.\n")
        w("![](figures/P2c_persistence.png)\n")

    w("### 1.2 Linear stability of the IaSC fixed point (poster heatmaps and (a, r) panels)\n")
    p1 = P.get("P1 stability heatmaps", {})
    rep = p1.get("representative", {})
    if rep:
        w("| modifier (k1, k2) | fraction stable, b = 0.2 | fraction stable, b = 0.02 |\n|---|---|---|")
        for k, v in rep.items():
            w(f"| {k} | {f(v['b02'])} | {f(v['b002'])} |")
        w("")
    w("Stable means the IaSC persists, because a rare M1 cannot invade. The (a, r) rectangle spans the whole "
      "polymorphism range a ∈ (b/(1+b), b/(1−b)) and r ∈ (0, 0.5]. All five poster summary points are reproduced:\n")
    w("1. k2 < 1 does not guarantee resolution; the stable fraction is large unless k1 is large.\n"
      "2. Weaker selection (b = 0.02) gives a larger stable fraction, i.e. less resolution.\n"
      "3. Larger a favours invasion.\n"
      "4. Smaller r favours invasion. Analytically, at r → 0 the invasion eigenvalue is 1 + b·k1/(2W_f) > 1 "
      "for any k1 > 0.\n"
      "5. In the small-effect corner (k1 ≤ 0.1, k2 ≥ 0.9) the outcome is very sensitive to k1 and k2.\n")
    w("![](figures/P1_stability_heatmaps.png)\n\n![](figures/P2a_ar_stability_grid.png)\n")
    p2 = P.get("P2 (a,r) maps + IBM invasion", {})
    if p2:
        w(f"**IBM test.** In {p2.get('n_cells')} parameter cells, IBM populations first reached their own IaSC state, "
          f"and then 2% of individuals mutated to M1. Verdicts on the ensemble-mean change over 300 generations "
          f"(95% CI): {p2.get('verdict_counts')}.\n")
        w(f"* Among decided cells, the direction agrees with the oracle trajectory from the same dose in "
          f"**{pct(p2.get('agreement_among_decided'))}** of cases, and with the linear-stability sign (λ > 1) in "
          f"{pct(p2.get('agreement_with_linear_stability'))}.")
        w(f"* log(IBM spread) vs log(oracle spread): r = {f(p2.get('log_ratio_corr'))}.")
        dis = p2.get("disagreements") or []
        if dis:
            w(f"* {len(dis)} cell{'s' if len(dis) != 1 else ''} disagree{'' if len(dis) != 1 else 's'}. λ = " +
              ", ".join(f(d['lam'], 4) for d in dis) + "; all are within about 0.5% of neutrality, where drift dominates.")
        w("")
        w("![](figures/P2b_invasion_ibm_vs_boundary.png)\n")

    w("### 1.3 Bifurcation diagrams (r = 0.1, b = 0.2)\n")
    p3 = P.get("P3 bifurcation", {})
    jumps = p3.get("det_jump_near", {})
    if jumps:
        w("Oracle invasion thresholds (the a at which M1 first fixes, starting near the fixed point), next to values "
          "read off the poster:\n")
        poster_read = {"k1=0.2, k2=0.2": "≈0.212", "k1=0.8, k2=0.8": "≈0.169", "k1=0.5, k2=0.5": "≈0.184",
                       "k1=0.2, k2=0.8": "≈0.193", "k1=0.8, k2=0.2": "≈0.176", "k1=0.5, k2=1": "≈0.166",
                       "k1=0, k2=0.5": "never"}
        w("| modifier | reconstruction | poster (read from plot) |\n|---|---|---|")
        for k, v in jumps.items():
            w(f"| {k} | {f(v, 4) if v is not None else 'never'} | {poster_read.get(k, '')} |")
        w("")
    w("IBM dots are ensemble means. Where M1 invades, a 2% dose still fails in some populations (lost to drift "
      "while rare), so mean M1 sits between 0 and 1. That mean is the empirical probability of resolution.\n")
    w("The **'away' panel** of the poster does not state its initial condition. Here pA1 = 0.5, pM1 = 0.75, D = 0. "
      "This reproduces the black curve's shape (a jump to A1 fixation, with M1 left at an intermediate value because "
      "it is neutral on an A1 background when k1 = 0). It does not reproduce the orange curve's M1 = 0.75 plateau for "
      "a < 1/6, which no generic initial condition gives. See *Open questions*.\n")
    w("![](figures/P3_bifurcation.png)\n")

    w("### 1.4 Size of perturbation needed, and basins\n")
    p4 = P.get("P4 thresholds", {})
    if p4:
        w("| case | oracle threshold | IBM logistic midpoint | IBM transition width |\n|---|---|---|---|")
        for k, v in p4.get("logistic_fits", {}).items():
            w(f"| {k} | {f(v['det'])} | {f(v['x50'])} | {f(v['width'])} |")
        w("\nThe oracle threshold is a separatrix (bistability). In the IBM it becomes a sigmoid whose midpoint "
          "approaches the oracle threshold as N grows and whose width shrinks.\n")
    w("![](figures/P4_thresholds.png)\n")
    p5 = P.get("P5 basins", {})
    if p5:
        w(f"Per-initial-condition agreement between IBM endpoints and oracle endpoints (same founders): "
          f"{p5.get('per_ic_agreement')}.\n")
    w("![](figures/P5_basins.png)\n")

    w("### 1.5 Convergence and animation\n")
    p6 = P.get("P6 convergence", {})
    if p6:
        s = p6.get("sd_slope")
        sb = p6.get("sd_slope_N_ge_1000") or [None] * 3
        w(f"Between-population SD scales as N^{f(sb[0], 2)} for N ≥ 1000 (95% CI {f(sb[1], 2)} to {f(sb[2], 2)}), "
          "consistent with the diffusion expectation of −0.5. Over all N, including N ≤ 500, the slope is "
          f"{f(s[0], 2)} ({f(s[1], 2)} to {f(s[2], 2)}). It is steeper because small populations sometimes lose M1 "
          "outright, which adds a second source of variance. The ensemble mean converges onto the oracle "
          "trajectory.\n")
    w("![](figures/P6_convergence.png)\n")
    p7 = P.get("P7 animation", {})
    if p7:
        w(f"Animated bistability (`animations/poster_bistability.gif`): "
          f"{pct(p7.get('per_population_fate_agreement'))} of individual populations end in the basin the oracle "
          "predicts from their starting point.\n")
    w("![](figures/P7_animation_lastframe.png)\n")

    # ---------------------------------------------------------------- owen
    w("## 2. Parsons (1961) / Owen (1953)\n")
    o1, o2, o3, o4 = (O.get(k, {}) for k in ("O1 autosomal invasion", "O2 Parsons example",
                                              "O3 X-linked invasion", "O4 Owen bistability"))
    if o1:
        w(f"* **Autosomal (eq. 2.5)** h1b2 + h2b1 > 2b1b2: IBM verdicts {o1.get('verdicts')}; agreement among decided "
          f"cells **{pct(o1.get('agreement_among_decided'))}**; corr(λ, P(establish)) = "
          f"{f(o1.get('lambda_vs_establishment_corr'))}.")
    if o2:
        w(f"* **Parsons' worked example** (β1 = 0.05, β2 = −0.02): λ = {f(o2.get('lambda_'), 4)} > 1, so the gene "
          f"increases. The oracle equilibrium is p1 = {f(o2.get('det_final'), 4)} and the IBM median is "
          f"{f(o2.get('ibm_final_median'), 4)}. {pct(o2.get('ibm_fraction_increased'))} of IBM populations increased.")
    if o3:
        w(f"* **X-linked (eq. 3.6)**: IBM verdicts {o3.get('verdicts')}; agreement among decided "
          f"**{pct(o3.get('agreement_among_decided'))}**. The approximate (3.6) and exact conditions disagree in "
          f"{o3.get('approx_vs_exact_disagreements')} cells.")
    if o4:
        eq = o4.get("equilibria", [])
        w(f"* **Owen bistability**: {len(eq)} interior equilibria; stable flags {[e['stable'] for e in eq]}. "
          f"The cubic quoted in the earlier AI blueprint gives the same points. IBM basin agreement "
          f"**{pct(o4.get('basin_agreement'))}**. Misses lie next to the saddle, where drift decides.")
    w("\n![](figures/O1_autosomal_invasion.png)\n\n![](figures/O2_parsons_example.png)\n\n"
      "![](figures/O3_xlinked_invasion.png)\n\n![](figures/O4_owen_phase_portrait.png)\n")

    # ---------------------------------------------------------------- curse
    w("## 3. Mother's curse (Havird et al. 2019), formalised\n")
    c1, c2, c3, c4 = (Cc.get(k, {}) for k in ("C1 strong form", "C2 twofold rule", "C3 weak form", "C4 restorer"))
    if c1:
        w("* **Strong form.** The spread of a female-beneficial mito variant does not depend on how much it harms "
          "males. KS tests of IBM endpoint distributions against s_m = 0: " +
          "; ".join(f"{k}: D={f(v['D'], 2)}, p={f(v['p'], 2)}" for k, v in c1.get("ks_endpoint", {}).items()) + ".")
    if c2:
        bad = [r for r in c2.get("table", []) if r["verdict"] != "IBM: unresolved" and not r["agree"]]
        w(f"* **Twofold rule.** IBM direction verdicts {c2.get('verdicts')}; agreement with the oracle "
          f"**{pct(c2.get('agreement_among_decided'))}**. A male-sterilising mito variant spreads with any female "
          "benefit; the nuclear version needs female fitness > 2. This is Parsons' latent root with h2 = 0. " +
          "".join(f"The exception is the {r['kind']} variant at female fitness {f(r['female_fitness'], 2)} "
                  f"(λ = {f(r['lam'], 2)}): the oracle invades only to a low equilibrium (ratio {f(r['det_ratio'], 2)}), "
                  f"while the IBM mean ratio is {f(r['ibm_ratio'], 2)}. Close to the threshold, the invading allele "
                  "settles at a low frequency that drift often erases. " for r in bad))
    if c3:
        w("* **Weak form** (female-neutral). " + "; ".join(
            f"s_m={r['s_m']}: P(fix) = {f(r['P_fix'])} [{f(r['lo'])}, {f(r['hi'])}]" for r in c3.get("table", []))
          + ". The neutral expectation is the initial frequency.")
    if c4:
        for k, v in c4.items():
            w(f"* **Restorer, {k}**: oracle final restorer frequency {f(v['det_final']['restorer'])}; IBM P(restorer "
              f"lost) = {f(v['ibm_P_restorer_lost'])}, P(fixed) = {f(v['ibm_P_restorer_fixed'])}.")
    w("\n![](figures/C1_strong_mothers_curse.png)\n\n![](figures/C2_twofold_rule.png)\n\n"
      "![](figures/C3_weak_mothers_curse.png)\n\n![](figures/C4_restorer.png)\n")

    # ------------------------------------------------------------- extended
    E = S.get("extended", {})
    if E:
        ee = E.get("environment", {})
        w("## 4. Extended tests: classical sexual-antagonism theory, drift theory and ML analyses\n")
        w(f"_IBM backend for this suite: `{ee.get('ibm_backend', 'n/a')}` {('(' + ee['gpu_device'] + ')') if ee.get('gpu_device') else ''}; "
          "the X-linked and X/Y kernels always run on the CPU._\n")
        pmaps = E.get("E1/E2 polymorphism maps (+M1 GP)", {})
        if pmaps:
            w("### 4.1 Where can antagonistic polymorphism persist? (Kidwell 1977; Rice 1984; Fry 2010)\n")
            w("Protected polymorphism means both alleles increase when rare. The oracle uses Fry's eq. 3 (autosomes) and "
              "Rice's eq. 2 (X). Both were verified to equal Parsons' latent root at each boundary in 20,000 random "
              "parameter sets. The IBM runs two invasion experiments per cell. **M1** is a Gaussian-process denoiser "
              "fitted only to IBM outcomes; it recovers the emergent boundary, which is compared with the oracle region "
              "by intersection-over-union (IoU).\n")
            w("| genome / dominance | oracle area | GP-IBM area | IoU (GP) | IoU (raw grid) | decided cells agreeing |\n"
              "|---|---|---|---|---|---|")
            for k, v in pmaps.items():
                if isinstance(v, dict) and "oracle_area" in v:
                    w(f"| {k} | {f(v['oracle_area'], 2)} | {f(v['gp_area'], 2)} | {f(v['iou_gp'], 2)} | "
                      f"{f(v['iou_raw'], 2)} | {pct(v['cell_agreement'])} ({v['n_decided']}/{v['n_cells']}) |")
            w("\n![](figures/E1_E2_polymorphism_maps.png)\n")
        k3 = E.get("E3 Kimura fixation", {})
        if k3:
            w("### 4.2 Fixation probabilities (Kimura 1962) and their correction\n")
            w("| selection | RMSE vs Kimura (sex-averaged s) | within 2 SE | RMSE vs full diffusion | within 2 SE | "
              "RMSE vs deterministic |\n|---|---|---|---|---|---|")
            for k, v in k3.items():
                if isinstance(v, dict) and "rmse" in v:
                    w(f"| {k} | {f(v['rmse'])} | {pct(v['frac_within_2se'])} | {f(v.get('rmse_full_diffusion'))} | "
                      f"{pct(v.get('frac_within_2se_full'))} | {f(v['rmse_deterministic'])} |")
            w("\n**Reading.**\n\n"
              "* Under concordant selection the IBM follows Kimura. A female-beneficial mito variant follows the haploid "
              "formula with Ne = N/2, so it drifts twice as strongly; this is the quantitative basis of the drift effects in "
              "§3.\n"
              "* Kimura's sex-averaged formula fails for strongly antagonistic selection (s_f − s_m = 0.1). Expanding the "
              "recursion gives Δp ≈ pq[s̄ − p(s_f² + s_m²)]. The second-order term vanishes for a rare allele, so "
              "invasion still depends on s̄ alone. It opposes the allele more and more as it becomes common, so "
              "fixation is less likely than Kimura predicts, and the shortfall grows with N. This is the same term that "
              "creates Kidwell's wedge (protection roughly when 0 < s̄ < s_f² + s_m²).\n"
              "* The general diffusion formula, built from the full sex-specific recursion, restores agreement. This is the "
              "analytic correction the IBM asked for.\n")
            w("![](figures/E3_kimura.png)\n")
        m2 = E.get("M2 neural emulator", {})
        if m2:
            w("### 4.3 M2: can a neural network trained only on IBM data rediscover Kimura?\n")
            for k, v in m2.items():
                if isinstance(v, dict):
                    w(f"* **{k}**: RMSE vs IBM on held-out N = 800: {f(v['rmse_vs_ibm_test'])}; vs Kimura: "
                      f"{f(v['rmse_vs_kimura_test'])}.")
            w(f"* For reference, IBM vs Kimura on the same held-out points: {f(m2.get('ibm_vs_kimura_test'))}.\n")
            w("Given the diffusion scaling variable N·s, the emulator extrapolates to an unseen population size about "
              "as well as Kimura does. With generic inputs it cannot. So the IBM data support the Ns data-collapse that "
              "diffusion theory predicts.\n")
            w("![](figures/M2_emulator.png)\n")
        e4 = E.get("E4 XY linkage", {})
        if e4:
            w("### 4.4 Linkage to the sex-determining region (Rice 1987)\n")
            w(f"* IBM-vs-oracle agreement on whether the polymorphism is maintained: **{pct(e4.get('agreement'))}**.")
            w(f"* Oracle fraction of s_m values with polymorphism, by r: {e4.get('oracle_poly_fraction_by_r')}.")
            w(f"* IBM fraction: {e4.get('ibm_poly_fraction_by_r')}.")
            w(f"* RMSE of the Y−X allele-frequency difference: {f(e4.get('ld_rmse'))}.\n")
            w("Tighter linkage widens the conditions for polymorphism and moves the male-benefit allele onto the Y, as "
              "Rice predicted. In this IBM, sex is determined genetically, not by a coin flip.\n")
            w("![](figures/E4_xy_linkage.png)\n")
        e5 = E.get("E5 diffusion persistence", {})
        if e5:
            w("### 4.5 How long does the IaSC polymorphism of the poster survive drift?\n")
            w(f"* Backward Kolmogorov equation with Ne = N vs IBM mean persistence time: median |relative error| "
              f"{pct(e5.get('median_abs_rel_err'))}, max {pct(e5.get('max_abs_rel_err'))}.")
            w(f"* **Tuner:** Ne measured from the IBM's own fluctuations (Ne/N mean {f((e5.get('Ne_over_N') or {}).get('mean'), 2)}) "
              f"cuts this to median {pct(e5.get('median_abs_rel_err_calibrated'))}, max {pct(e5.get('max_abs_rel_err_calibrated'))}.")
            w("* The remaining gap is at the smallest N, where the continuous diffusion approximation is weakest.")
            w("* Persistence time grows roughly exponentially with N in the middle of the a-range. This makes the "
              "finite-population caveat of §1 quantitative.\n")
            w("![](figures/E5_diffusion_persistence.png)\n")
        m3 = E.get("M3 inverse problem", {})
        if m3:
            w("### 4.6 M3: inverse problem — recovering s_f and s_m from one IBM trajectory\n")
            w("| case | RMSE s_f | RMSE s_m | RMSE (s_f − s_m) | bias s_f | bias s_m |\n|---|---|---|---|---|---|")
            for k, v in m3.items():
                if isinstance(v, dict):
                    w(f"| {k} | {f(v['rmse_s_f'])} | {f(v['rmse_s_m'])} | {f(v['rmse_difference'])} | "
                      f"{f(v['bias_s_f'])} | {f(v['bias_s_m'])} |")
            w("\nThe trajectory pins down the *difference* s_f − s_m far better than either coefficient on its own; the "
              "oracle fit is best for the difference. That is an identifiability limit of additive SA selection. In small "
              "populations the oracle fit degrades because drift is unmodelled noise. The IBM-trained network is more "
              "robust there, so simulation-based inference is the safer choice for real (finite) data.\n")
            w("![](figures/M3_inverse_problem.png)\n")

    w("## 5. Open questions for the authors\n")
    w("1. **Life cycle.** We assumed haploid selection in each sex, then random union, then meiosis with "
      "recombination, and then sex assigned at random. This reproduces the poster's p* and invasion thresholds. "
      "Is it the intended cycle?\n"
      "2. **'Fraction of parameter space'.** We read this as the fraction of the (a, r) rectangle "
      "(b/(1+b), b/(1−b)) × (0, 0.5]. Is that the domain and resolution used?\n"
      "3. **'Away from the fixed point'.** Which initial condition was used, and how many generations were "
      "iterated? The orange plateau at M1 = 0.75 for a < 1/6 is not an attractor of the reconstructed map.\n"
      "4. **Size-of-perturbation panel.** Which r was used? We assumed r = 0.1.\n")
    with open(os.path.join(RES, "REPORT.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print("wrote", os.path.join(RES, "REPORT.md"))


if __name__ == "__main__":
    sys.exit(main())
